version: '3.7'

services:
  artisanwriting:
    image: artisanwriting

    env_file:
      # VIRTUAL_HOST=artisanwriting.example.com
      # VIRTUAL_PORT=3000
      #LETSENCRYPT_HOST=artisanwriting.example.com
      # NUXT_HOST=0.0.0.0
      # BROWSER_BASE_URL=https://artisanwriting.example.com
      - .env
    
    secrets:
      - source: artisanwriting.postgres_user
        target: /run/secrets/postgres_user
      - source: artisanwriting.postgres_password
        target: /run/secrets/postgres_password

    networks:
      - ingress-net
      - postgres-net

secrets:
  artisanwriting.postgres_user:
    external: true
  
  artisanwriting.postgres_password:
    external: true

networks:
  ingress-net:
    external: true
  
  postgres-net:
    external: true
