INSERT INTO tag VALUES (7,'Light',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO tag VALUES (8,'Tapestry',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO tag VALUES (9,'Crystal',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO tag VALUES (10,'Void',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO tag VALUES (11,'NONE',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);